#Tensor Flow 

**A. Shows how you can create a session in Tensor Flow

#Answer

In [1]:
import tensorflow as tf

In [7]:
a=tf.constant(10)

In [3]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [53]:
tf.compat.v1.disable_eager_execution()# need to disable eager in TF2.x
# Build a graph.
con1=tf.constant(10)
con2=tf.constant(20)
# Launch the graph in a session.
sess=tf.compat.v1.Session()
# Evaluate the tensor `con1`,'con2'.
sess.run([con1,con2])

[10, 20]

In [54]:
tf.compat.v1.disable_eager_execution() # need to disable eager in TF2.x
# Build a graph.
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b

# Launch the graph in a session.
sess = tf.compat.v1.Session()

# Evaluate the tensor `c`.
print(sess.run(c)) # prints 30.0

30.0


**B. Define constants and perform computation such as addition and subtraction with those
constants using the session.

#Answer

#Def:  Constants are primary elements whose value does not change

In [16]:
#Addition
tf.compat.v1.disable_eager_execution() # need to disable eager in TF2.x
# Build a graph.
a = tf.constant(24)
b = tf.constant(33)
c = a+b

# Launch the graph in a session.
sess = tf.compat.v1.Session()

# Evaluate the tensor `c`.
print(sess.run(c)) # prints 57

57


In [17]:
#Subtraction
#Addition
tf.compat.v1.disable_eager_execution() # need to disable eager in TF2.x
# Build a graph.
a = tf.constant(100.0)
b = tf.constant(33.0)
c = a-b

# Launch the graph in a session.
sess = tf.compat.v1.Session()

# Evaluate the tensor `c`.
print(sess.run(c)) # prints 67.0

67.0


**C. Print Hello World using the same

In [55]:
tf.compat.v1.disable_eager_execution() # need to disable eager in TF2.x
# Build a graph.
str= tf.constant("Hello World")


# Launch the graph in a session.
sess = tf.compat.v1.Session()

# Evaluate the tensor `c`.
print(sess.run(str)) # prints 'Hello World'

b'Hello World'


**D. Create a simple Linear Equation y = mx+c in tensor flow, where m and c are variables
and x is a placeholder
a. Feed in a scalar value to x
b. Feed in a vector of 5 values to x
c. Choose arbitrary values for m and c

In [43]:
#a. Feed in a scalar value to x
sess = tf.compat.v1.Session()
x = tf.compat.v1.placeholder(tf.int32)

In [35]:
#b. Feed in a vector of 5 values to x
m=tf.compat.v1.Variable([10],tf.int32)
c=tf.compat.v1.Variable([5],tf.int32)

In [46]:
init = tf.compat.v1.global_variables_initializer()
y=m*x+c

In [47]:
sess.run(init)

In [48]:
sess.run(y,feed_dict={x:[1,2,3,4,5]})

array([15, 25, 35, 45, 55])

In [50]:
#c1. Choose arbitrary values for m and c
sess = tf.compat.v1.Session()
x = tf.compat.v1.placeholder(tf.int32)
m=tf.compat.v1.Variable([6],tf.int32)
c=tf.compat.v1.Variable([5],tf.int32)
init = tf.compat.v1.global_variables_initializer()
y=m*x+c
sess.run(init)
sess.run(y,feed_dict={x:[1,2,3,4,5]})

array([11, 17, 23, 29, 35])

In [56]:
#c2. Choose arbitrary values for m and c
sess = tf.compat.v1.Session()
x = tf.compat.v1.placeholder(tf.int32)
m=tf.compat.v1.Variable([1],tf.int32)
c=tf.compat.v1.Variable([6],tf.int32)
init = tf.compat.v1.global_variables_initializer()
y=m*x+c
sess.run(init)
sess.run(y,feed_dict={x:[1,2,3,4,5]})

array([ 7,  8,  9, 10, 11])