In [2]:
!pip install scikit-learn

     ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
     ---------------------------------------- 0.0/8.3 MB 1.3 MB/s eta 0:00:07
     ---------------------------------------- 0.1/8.3 MB 1.1 MB/s eta 0:00:08
      --------------------------------------- 0.1/8.3 MB 930.9 kB/s eta 0:00:09
      --------------------------------------- 0.1/8.3 MB 853.3 kB/s eta 0:00:10
      --------------------------------------- 0.1/8.3 MB 853.3 kB/s eta 0:00:10
      --------------------------------------- 0.2/8.3 MB 653.6 kB/s eta 0:00:13
      --------------------------------------- 0.2/8.3 MB 653.6 kB/s eta 0:00:13
     - -------------------------------------- 0.3/8.3 MB 803.7 kB/s eta 0:00:10
     - -------------------------------------- 0.3/8.3 MB 679.4 kB/s eta 0:00:12
     - -------------------------------------- 0.4/8.3 MB 768.6 kB/s eta 0:00:11
     - -------------------------------------- 0.4/8.3 MB 798.7 kB/s eta 0:00:10
     - -------------------------------------- 0.4/8.3

In [3]:
import pandas as pd
from sklearn import datasets

In [4]:
from sklearn.datasets import load_wine
wine=load_wine()

In [5]:
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [6]:
df=pd.DataFrame(wine.data,columns=wine.feature_names)
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols   
0    14.23        1.71  2.43               15.6      127.0           2.80  \
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue   
0        3.06                  0.28             2.29             5.64  1.04  \
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [7]:
df['target']=wine.target
df['target']=df['target'].apply(lambda x:wine.target_names[x])

In [8]:
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols   
0    14.23        1.71  2.43               15.6      127.0           2.80  \
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue   
0        3.06                  0.28             2.29             5.64  1.04  \
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline   target  
0                          3.92   1065.0  class_0  
1                          3.40   1050.0  class_0  
2                          3.17   1185.0  class_0  
3                          3.45   1480.0  class_0  
4                          2.93    735.0  class_0

In [9]:
df.target.unique()

array(['class_0', 'class_1', 'class_2'], dtype=object)

In [10]:
x=df.iloc[:,:13]
x


alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols   
0      14.23        1.71  2.43               15.6      127.0           2.80  \
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue   
0          3.06                  0.28             2.29             5.64  1.04  \
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [18]:
y=df['target']
y

0      0
1      0
2      0
3      0
4      0
      ..
173    2
174    2
175    2
176    2
177    2
Name: target, Length: 178, dtype: int32

In [11]:
from sklearn.preprocessing import LabelEncoder
le_target= LabelEncoder()
df['target']=le_target.fit_transform(df['target'])
df.sample(2)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols   
104    12.51        1.73  1.98               20.5       85.0           2.20  \
28     13.87        1.90  2.80               19.4      107.0           2.95   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue   
104        1.92                  0.32             1.48             2.94  1.04  \
28         2.97                  0.37             1.76             4.50  1.25   

     od280/od315_of_diluted_wines  proline  target  
104                          3.57    672.0       1  
28                           3.40    915.0       0

In [12]:
df['target'].value_counts()

target
1    71
0    59
2    48
Name: count, dtype: int64

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_scaled=sc.fit_transform(x)
x_scaled[1:15]

array([[ 0.24628963, -0.49941338, -0.82799632, -2.49084714,  0.01814502,
         0.56864766,  0.73362894, -0.82071924, -0.54472099, -0.29332133,
         0.40605066,  1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, -0.2687382 ,  0.08835836,
         0.80899739,  1.21553297, -0.49840699,  2.13596773,  0.26901965,
         0.31830389,  0.78858745,  1.39514818],
       [ 1.69154964, -0.34681064,  0.4879264 , -0.80925118,  0.93091845,
         2.49144552,  1.46652465, -0.98187536,  1.03215473,  1.18606801,
        -0.42754369,  1.18407144,  2.33457383],
       [ 0.29570023,  0.22769377,  1.84040254,  0.45194578,  1.28198515,
         0.80899739,  0.66335127,  0.22679555,  0.40140444, -0.31927553,
         0.36217728,  0.44960118, -0.03787401],
       [ 1.48155459, -0.51736664,  0.30515936, -1.28970717,  0.86070511,
         1.56209322,  1.36612798, -0.17609475,  0.66421706,  0.73186953,
         0.40605066,  0.33660575,  2.23903902],
       [ 1.71625494, -0.418623

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.2)

In [22]:
print(x_train.shape)

(142, 13)


In [39]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Dense(512, activation='relu', input_shape=[13]),
    layers.Dense(512, activation='relu'),
    layers.Dense(512, activation='relu'),
    layers.Dense(1),
])

In [48]:
model.compile(
    optimizer='adam',
    loss='mae',
     metrics=['accuracy'])
model.fit(x_train, y_train,validation_data=(x_test, y_test),
 epochs=10)

Epoch 1/10
5/5 [==============================] - 1s 105ms/step - loss: 0.1159 - accuracy: 0.7394 - val_loss: 0.1811 - val_accuracy: 0.6944
Epoch 2/10
5/5 [==============================] - 0s 27ms/step - loss: 0.1409 - accuracy: 0.7394 - val_loss: 0.1761 - val_accuracy: 0.6667
Epoch 3/10
5/5 [==============================] - 0s 25ms/step - loss: 0.0989 - accuracy: 0.7394 - val_loss: 0.1206 - val_accuracy: 0.6944
Epoch 4/10
5/5 [==============================] - 0s 21ms/step - loss: 0.0861 - accuracy: 0.7394 - val_loss: 0.1433 - val_accuracy: 0.6944
Epoch 5/10
5/5 [==============================] - 0s 24ms/step - loss: 0.0693 - accuracy: 0.7394 - val_loss: 0.1321 - val_accuracy: 0.6944
Epoch 6/10
5/5 [==============================] - 0s 22ms/step - loss: 0.0655 - accuracy: 0.7394 - val_loss: 0.1226 - val_accuracy: 0.6944
Epoch 7/10
5/5 [==============================] - 0s 20ms/step - loss: 0.0616 - accuracy: 0.7394 - val_loss: 0.0935 - val_accuracy: 0.6944
Epoch 8/10
5/5 [==========

In [50]:
from sklearn.metrics import confusion_matrix , classification_report
import numpy as np
y_pred = model.predict(x_test)
y_pred_classes = [np.argmax(element) for element in y_pred]

print("Classification Report: \n", classification_report(y_test, y_pred_classes))

2/2 [==============================] - 0s 16ms/step
Classification Report: 
               precision    recall  f1-score   support

           0       0.31      1.00      0.47        11
           1       0.00      0.00      0.00        14
           2       0.00      0.00      0.00        11

    accuracy                           0.31        36
   macro avg       0.10      0.33      0.16        36
weighted avg       0.09      0.31      0.14        36



C:\Users\ysadmin\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ysadmin\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ysadmin\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [51]:
model.layers[0].get_weights()[1]

array([ 1.06144324e-02, -1.59429188e-03, -7.86232855e-03,  1.22732879e-03,
       -8.69471580e-03, -2.68905237e-03,  8.74269195e-03, -1.06244599e-02,
       -2.18236502e-02,  5.79932530e-04, -3.87434028e-02, -9.40358732e-03,
       -2.09281556e-02,  2.41416926e-03, -1.13807945e-02, -2.65174173e-02,
       -2.62357090e-02,  2.18311208e-03, -2.12656558e-02, -7.57923862e-03,
       -2.64519248e-02, -1.37613639e-02, -2.31306627e-02,  1.15983626e-02,
       -1.65326206e-03, -2.34329961e-02, -2.86217709e-03,  5.81983756e-03,
       -2.26899404e-02,  4.21025464e-03, -8.23254290e-04, -2.54528224e-02,
        1.69632658e-02, -1.97148006e-02, -1.27469394e-02,  2.24424020e-05,
        5.98567072e-03, -7.21592735e-03,  5.53237647e-03,  5.10670245e-03,
       -1.91968884e-02, -8.07056110e-03, -2.31076684e-02,  4.73668939e-03,
        1.00161266e-02,  3.63356550e-03, -2.37899888e-02,  4.00704890e-03,
        3.24665103e-04, -3.41843143e-02, -5.62662445e-03,  6.74830470e-03,
        1.59115829e-02,  

In [62]:
weights = model.layers[1].get_weights()[0]
weights

array([[-0.04688799, -0.01575335, -0.02189852, ..., -0.04857141,
         0.03606291,  0.031641  ],
       [-0.04946943, -0.07614338, -0.07818921, ..., -0.00175767,
         0.05271724, -0.04856552],
       [-0.05224592,  0.0130617 ,  0.03519917, ..., -0.03773629,
         0.0426214 ,  0.0030672 ],
       ...,
       [ 0.06956747, -0.06106257,  0.04232527, ...,  0.02569827,
         0.01382792,  0.00798977],
       [-0.03862622, -0.07362322,  0.02514482, ..., -0.04408774,
         0.01404054, -0.01815816],
       [-0.06077707,  0.04883107, -0.02888887, ...,  0.0381866 ,
         0.03158449,  0.0326742 ]], dtype=float32)

In [63]:
biases = model.layers[1].get_weights()[1]
biases

array([-3.96787096e-03, -1.18375225e-02, -1.39670866e-02,  1.06958831e-02,
       -8.29557143e-03, -7.88763072e-03, -1.38784153e-02,  1.03717688e-02,
       -4.17143945e-03,  8.90562031e-03, -3.69281764e-03, -7.67978979e-03,
        1.46470568e-03,  1.61020607e-02, -7.81583507e-03, -9.15012043e-03,
       -5.40973479e-03,  1.45752449e-03, -4.82263137e-03,  1.56002789e-04,
        2.04911176e-03, -1.06208203e-02, -7.32953614e-03, -6.57246914e-03,
       -1.53216841e-02, -8.99366476e-03,  1.51502546e-02,  1.19032348e-02,
        8.43314920e-03, -6.25023060e-03,  9.56811663e-03,  1.05101697e-03,
        9.31381807e-03,  1.21598030e-02,  2.90609291e-03, -5.99050755e-03,
       -4.72880946e-03, -8.81634839e-03, -3.88964836e-04,  1.34221604e-02,
       -7.87287205e-03, -1.14043728e-02,  2.30185804e-03, -5.40223485e-03,
        3.11963633e-03,  6.43929513e-03, -4.32036258e-03,  9.26093431e-04,
       -8.56508128e-03,  7.54742138e-03, -2.82354024e-03,  3.90642881e-03,
        6.04602275e-03, -

In [64]:
print("learned weights =", weights)

learned weights = [[-0.04688799 -0.01575335 -0.02189852 ... -0.04857141  0.03606291
   0.031641  ]
 [-0.04946943 -0.07614338 -0.07818921 ... -0.00175767  0.05271724
  -0.04856552]
 [-0.05224592  0.0130617   0.03519917 ... -0.03773629  0.0426214
   0.0030672 ]
 ...
 [ 0.06956747 -0.06106257  0.04232527 ...  0.02569827  0.01382792
   0.00798977]
 [-0.03862622 -0.07362322  0.02514482 ... -0.04408774  0.01404054
  -0.01815816]
 [-0.06077707  0.04883107 -0.02888887 ...  0.0381866   0.03158449
   0.0326742 ]]


In [65]:
# Biases are similar because they are all initialized with zeros (by default).
print("learned biases =", biases)


learned biases = [-3.96787096e-03 -1.18375225e-02 -1.39670866e-02  1.06958831e-02
 -8.29557143e-03 -7.88763072e-03 -1.38784153e-02  1.03717688e-02
 -4.17143945e-03  8.90562031e-03 -3.69281764e-03 -7.67978979e-03
  1.46470568e-03  1.61020607e-02 -7.81583507e-03 -9.15012043e-03
 -5.40973479e-03  1.45752449e-03 -4.82263137e-03  1.56002789e-04
  2.04911176e-03 -1.06208203e-02 -7.32953614e-03 -6.57246914e-03
 -1.53216841e-02 -8.99366476e-03  1.51502546e-02  1.19032348e-02
  8.43314920e-03 -6.25023060e-03  9.56811663e-03  1.05101697e-03
  9.31381807e-03  1.21598030e-02  2.90609291e-03 -5.99050755e-03
 -4.72880946e-03 -8.81634839e-03 -3.88964836e-04  1.34221604e-02
 -7.87287205e-03 -1.14043728e-02  2.30185804e-03 -5.40223485e-03
  3.11963633e-03  6.43929513e-03 -4.32036258e-03  9.26093431e-04
 -8.56508128e-03  7.54742138e-03 -2.82354024e-03  3.90642881e-03
  6.04602275e-03 -6.47831848e-03 -9.74153634e-03 -7.68520124e-03
 -5.40903118e-03 -1.10249342e-02  1.63546344e-03 -5.67336893e-03
 -8.9395

In [66]:
len(weights)

512

In [67]:
len(biases)

512